### ISSUE TITLE
GenomicRegion.o

### ISSUE THREAD

**Issue by henricheng** [smithlabcode/piranha#14]
I'm trying to install the piranha but when I do "make all" it spits out this error. I've tried to download it from GitHub "git clone --recursive ......" and download it with tar from the lab site but it seems like that file isn't in either of those folders.

g++ -Wall -fPIC -fmessage-length=50 -arch x86_64 -stdlib=libstdc++ -O3 -c -o /Users/chengh1/Downloads/piranha-1.2.1/src/smithlab_cpp/GenomicRegion.o /Users/chengh1/Downloads/piranha-1.2.1/src/smithlab_cpp/GenomicRegion.cpp -I/Users/chengh1/Downloads/piranha-1.2.1/src/smithlab_cpp -I../common/
warning: include path for stdlibc++ headers not
      found; pass '-stdlib=libc++' on the command
      line to use the libc++ standard library
      instead [-Wstdlibcxx-not-found]
In file included from /Users/chengh1/Downloads/piranha-1.2.1/src/smithlab_cpp/GenomicRegion.cpp:23:
In file included from /Users/chengh1/Downloads/piranha-1.2.1/src/smithlab_cpp/GenomicRegion.hpp:27:
/Users/chengh1/Downloads/piranha-1.2.1/src/smithlab_cpp/smithlab_utils.hpp:27:10: fatal error: 
      'string' file not found
#include <string>
         ^~~~~~~~
1 warning and 1 error generated.
make[2]: *** [/Users/chengh1/Downloads/piranha-1.2.1/src/smithlab_cpp/GenomicRegion.o] Error 1
make[1]: *** [all] Error 2
make: *** [all] Error 2

**Comment by andrewdavidsmith** [comment]
Unfortunately if the `string` header is not found, then you likely have some problems in how your compiler is setup. I've seen this with gcc installations on more recent macos (you didn't mention which os you use, but it's obviously Mac).

**Comment by henricheng** [comment]
Hi, I'm trying to run it on my Linux instead. But it is having trouble connecting to the gsl. I know it's downloaded but piranha doesn't seem to be able to find it. Is there a way to direct it when executing ./configure?

**Comment by henricheng** [comment]
./configure --bindir=/usr/bin/gsl
I've tried this but it doesn't work.

**Comment by santataRU** [comment]
> Unfortunately if the `string` header is not found, then you likely have some problems in how your compiler is setup. I've seen this with gcc installations on more recent macos (you didn't mention which os you use, but it's obviously Mac).

Dear Andrew,

I encountered the similar issues while I was trying to install Piranha in MacOS with M1 chip. Error messages attached:

(base) bieniaszlab@pauls-imac-2 piranha % make all
make[1]: Entering directory '/Users/bieniaszlab/Documents/Xiao/Literature/Piranha/piranha/src'
make[2]: Entering directory '/Users/bieniaszlab/Documents/Xiao/Literature/Piranha/piranha/src/progs'
g++ -Wall -fPIC -fmessage-length=50 -arch x86_64 -stdlib=libstdc++ -O3 -c -o /Users/bieniaszlab/Documents/Xiao/Literature/Piranha/piranha/src/smithlab_cpp/GenomicRegion.o /Users/bieniaszlab/Documents/Xiao/Literature/Piranha/piranha/src/smithlab_cpp/GenomicRegion.cpp -I/Users/bieniaszlab/Documents/Xiao/Literature/Piranha/piranha/src/smithlab_cpp -I../common/
clang++: warning: include path for
      libstdc++ headers not found; pass
      '-stdlib=libc++' on the command line to use
      the libc++ standard library instead
      [-Wstdlibcxx-not-found]
In file included from /Users/bieniaszlab/Documents/Xiao/Literature/Piranha/piranha/src/smithlab_cpp/GenomicRegion.cpp:23:
In file included from /Users/bieniaszlab/Documents/Xiao/Literature/Piranha/piranha/src/smithlab_cpp/GenomicRegion.hpp:27:
/Users/bieniaszlab/Documents/Xiao/Literature/Piranha/piranha/src/smithlab_cpp/smithlab_utils.hpp:27:10: fatal error: 
      'string' file not found
   27 | #include <string>
      |          ^~~~~~~~
1 error generated.
make[2]: *** [Makefile:55: /Users/bieniaszlab/Documents/Xiao/Literature/Piranha/piranha/src/smithlab_cpp/GenomicRegion.o] Error 1
make[2]: Leaving directory '/Users/bieniaszlab/Documents/Xiao/Literature/Piranha/piranha/src/progs'
make[1]: *** [Makefile:10: all] Error 2
make[1]: Leaving directory '/Users/bieniaszlab/Documents/Xiao/Literature/Piranha/piranha/src'
make: *** [Makefile:27: all] Error 2

**Comment by andrewdavidsmith** [comment]
I don't think anyone has tested the extent to which Piranha should build on new Mac chips. It would be great if someone looked into this.

**Comment by santataRU** [comment]
> I don't think anyone has tested the extent to which Piranha should build on new Mac chips. It would be great if someone looked into this.

Thanks, Andrew. Another potential issue could be the Python version; it seems that Piranha is only compatible with Python 2, which is obsolete now.

**Comment by andrewdavidsmith** [comment]
That's a separate issue, but the Python is just boilerplate in a script. It could probably just be extracted directly.
