### ISSUE TITLE
Version number is wrong in configure.ac

### ISSUE THREAD

**Issue by pjuren** [smithlabcode/piranha#2]
The configure.ac contains the wrong version number, and so by extension the configure script does too.

**Comment by bahramis** [comment]
Fixed

**Comment by pjuren** [comment]
Not quite... still a few things to take care of:

* you updated configure.ac, but didn't rebuild the configure script
* currently the version number is hardcoded into Piranha.cpp; it should be written to config.hpp when configure builds this file and then Piranha.cpp should get it from there.

Time to learn how autoconf works? ;-)
