### ISSUE TITLE
Recent updates cause Piranha to fail when processing data from the simulate program

### ISSUE THREAD

**Issue by pjuren** [smithlabcode/piranha#3]
Steps to reproduce bug:

    > Simulate -d ZeroTruncatedNegativeBinomialRegression -n 1000 -r response.bed -c "cov1.bed cov2.bed"
    > Pirhana response.bed cov1.bed cov2.bed

Result

    ERROR:	aggregating genomic regions failed -- didn't get the same number of covariates values for all covariates

**Comment by pjuren** [comment]
Output from previous version (version 1.2.0)

    chr2	86584	86585	X	119	+	0.00835524	0.725411	0.730927
    chr2	414809	414810	X	157	+	0.00208321	0.727797	0.103537
    chr2	494007	494008	X	198	+	0.00448546	0.872083	0.51432
    chr3	304118	304119	X	171	+	0.00835524	0.921943	0.480905
    chr3	620300	620301	X	139	+	0.00835524	0.744381	0.901363
    chr5	667766	667767	X	182	+	0.00208321	0.657859	0.99564
    chr5	897917	897918	X	131	+	0.00448546	0.703624	0.471604

**Comment by bahramis** [comment]
Fixed.
