### ISSUE TITLE
Cannot install: GSL linking problem

### ISSUE THREAD

**Issue by taran-sh** [smithlabcode/piranha#7]
Hi,

I tried to install Piranha 1.2.1 on my computer (macOS 10.12.1)
I installed GSL (v2.3) with homebrew (`brew install gsl`). I checked that GSL is properly installed to my PATH (`gsl-config` works).

As I typed `./configure` however, It returned an error:

```
configure: error: could not find or link to GSL -- Piranha requires GSL and cannot be
built without it. GSL can be downloaded from http://www.gnu.org/software/gsl/ -- 
please ensure GSL is correctly installed on your system.
```

Even though GSL was installed, it says it cannot find GSL.

I tried configuring Piranha again after removing GSL v2.3 and reinstalling GSL v1.14 but it did not solved the problem.

Can you please help me with installation?

Thanks.

**Comment by pjuren** [comment]
Hi,

I think home-brew installs GSL in a location that is not automatically searched on recent version of MacOS. I think this link explains the problem you are having:

http://stackoverflow.com/questions/23905661/on-mac-g-clang-fails-to-search-usr-local-include-and-usr-local-lib-by-def

Try the suggested solution of installing the Xcode developer tools to get the compiler to automatically search those directories. You might then need to close and re-open your terminal for changes to take effect.

- Phil

**Comment by maheshmathe** [comment]
Hello. I am facing the same issue on centos. I installed piranha using conda. It did not link bamtools to it. While trying to configure it manually, I am unable to link the gsl library. How to link the gsl library while configuring?

This is the error I keep getting: 

configure: WARNING: unrecognized options: --with-bam_tools_headers, --with-bam_tools_library, --with-gsl
provided BAMTools headers directory is /home/anaconda2/pkgs/bamtools-2.5.1-he860b03_5/include
provided BAMTools library directory is /home/anaconda2/pkgs/bamtools-2.5.1-he860b03_5/lib
checking for C++ compiler default output file name... a.out
checking whether the C++ compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether /home/ashish/anaconda2/bin/x86_64-conda_cos6-linux-gnu-c++ accepts -g... yes
checking whether we're compiling on Darwin/MacOS... no
checking for cos in -lm... yes
checking for cblas_dgemm in -lgslcblas... no
checking for gsl_blas_dgemm in -lgsl... no
checking for linking against gsl matrix... no
configure: error: could not find or link to GSL -- Piranha requires GSL and cannot be built without it. GSL can be downloaded from http://www.gnu.org/software/gsl/ -- please ensure GSL is correctly installed on your system.

**Comment by IrisWEI-1996** [comment]
I met the same problem though I'm using Fedora,Linux.  
After confirming the successful instalment of GSL, I failed to configure Piranha even 
`./configure --prefix=/home/name/gsl`

Instead, I successfully install Piranha with conda instalment.

**Comment by reformist** [comment]
I'm having trouble running ./configure as well on a Mac OS system. After confirming GSL installment, I can't link GSL. I've tried xcode-select --install and ./configure CFLAGS="-I/opt/homebrew/Cellar/gsl/2.7.1/include" LDFLAGS="-L/opt/homebrew/Cellar/gsl/2.7.1/lib -lgsl -lgslcblas -lm"

below is my error statement
checking for g++... g++
checking for C++ compiler default output file name... a.out
checking whether the C++ compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether we're compiling on Darwin/MacOS... yes
configure: no BAMTools headers directory specified
configure: no BAMTools library directory specified
checking for cos in -lm... yes
checking for cblas_dgemm in -lgslcblas... no
checking for gsl_blas_dgemm in -lgsl... no
checking for linking against gsl matrix... no
configure: error: could not find or link to GSL -- Piranha requires GSL and cannot be built without it. GSL can be downloaded from http://www.gnu.org/software/gsl/ -- please ensure GSL is correctly installed on your system

**Comment by andrewdavidsmith** [comment]
@reformist Any chance you can create a new issue, and I'll close this one and try to respond to the new one? Things are too different now from when this issue was first created, so it won't really be the same situation. Just copy-paste your stuff from here into the new issue.

**Comment by andrewdavidsmith** [comment]
Closing this issue because macOS is even harder to deal with than when it was first opened, so the solutions are likely not relevant to those who initially opened it. See issue #19
