### ISSUE TITLE
-p default value?

### ISSUE THREAD

**Issue by hershbc** [smithlabcode/piranha#9]
Hello,
I've been working with your CLIP-peak finder, but I am getting far fewer significant peaks than I expect.  The data has several hundred peaks that have a peak height of at least 20 tags, background levels look very low when visualized on a genome browser.  When I run Piranha, around 40 peaks are called significant.  Our end goal in using Piranha is to be able to better compare two CLIPs that have different expression patterns, so we are using RNA-Seq as a covariate.  My PI has suggested changing the -p parameter to potentially make the program a little more liberal in peak calling.  However, I don't know what the default value is.  I would guess that it might be 0.05, since that is a value often associated with significance, but I am not sure.  Could you tell me what the default value of this parameter is?  

I have already altered -z (200, 100, 50, 10) and it has had very little effect on number of peaks found.

**Comment by pjuren** [comment]
The default p-value is 0.01. However, depending on how your experiment is set up (and what kind of assay you're using), there will likely be better ways to make the program more liberal than adjusting the p-value threshold. 

It will be easier to discuss via email. You can contact me directly here: philip <dot> uren <at> gmail <dot> com; replace <dot> and <at> with '.' and '@' respectively.

**Comment by pjuren** [comment]
Sorry, email address got mangled:
philip {dot} uren {at} gmail {dot} com
(replace {dot} and {at} with '.' and '@')
